name: loopflutter
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  salomon_bottom_bar: ^3.3.2
  http: ^1.1.1
  shared_preferences: ^2.5.3
  image_picker: ^1.0.4
  permission_handler: ^11.0.1
  country_code_picker: ^3.4.0
  url_launcher: ^6.2.2
  file_picker: ^8.0.0+1
  path: ^1.9.0
  uuid: ^4.4.0
  socket_io_client: ^2.0.3+1
  font_awesome_flutter: ^10.7.0
  video_player: ^2.8.2
  geolocator: ^11.0.0
  geocoding: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  generate: true
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    # - assets/Background.png
    - assets/profileBackgroundImage.png
    - assets/serverProviderBackground.png
    - assets/defaultProfileImage.png
    - assets/chatbg.png
    - assets/support.png
    - assets/BackgroundLogo.png
  #   - images/a_dot_ham.jpeg

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/BackgroundLogo.png"
  min_sdk_android: 21
  remove_alpha_ios: true